sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/minecraft-server
    - secure: "dU5Q8RCn7zNa+Jin+wiWHRb7yEiboEJ0WcSJy7gblqYGJVCku/R5qu7soGQsYwAgFusVik5PIvHsdnj5ek6NvS/nthDnP7y+/zV9Q5Ju9kQPpUTSlyI7RLkA3BDVrGrwhziAPkPy6qkIypztSHKFDNpYoz9XZkoHOYsQmIE8UoD3gjWgmmhquLAWFkJdoD8RAOduvQgQ0A9g2XxW0p2bFQ9bK7WSneQNB1YB/PHKVwqTZLjyJTFcuwfrfEGFIU2TZgQoyepc0x7MvnHLz9tOSVweyfuu8tOGeCd/8/8xp993J/AHkhiJE/jJfB3j/KbvTw7gJeHN/5z4VoXt6g3VxlOlskSNZX0Ycyiq98vOvHC1dl4Nc0n+gg6RSHTMEU7yyFcziI13VXgVPLmy145N2cer6DXyELFKCvoQeIOzgQ6KPIPMt/Zy0qSzgI3OYHimPMgqqtXRgCnmnqJtu4SFTu9TIM2JRGoKrU2cj+8fndDSYs5WNMdMBQ/TSy7YZ5TlkjVfBgqIDsLrUQPDvdiEwSQ6DMiQjSqvgpQClQIUv6zVfiFGBgKh+AasQ5HlbU9F+KyJlBEM7CfOSs+gaKriwf5TOEl+rgyqJoHm+SD8JjA1WDq8SWr/hvyyIyg9abQb9EFXX+dGHH4dA+U+qvDtUNxxBdc+NbDYeqBWap5exSI="
